spring.datasource.url=jdbc:mariadb://localhost:3306/letterbooks
spring.datasource.username=letter_user
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=validate
# Obliga a Hibernate a usar los nombres exactos de las anotaciones @Table y @Column
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl